os: linux
dist: focal
language: node_js
node_js:
    - '10'
    - '11'
    - '12'
    - '13'
    - '14'
cache: npm
script:
    - npm run clean
    - npm run prettier-check
    - npm run build
    - npm run test
    - npm run docs
    - ./bin/leasot --help
    - ./bin/leasot-reporter --help
deploy:
    provider: npm
    edge: true
    skip_cleanup: true
    cleanup: false
    api_token:
        secure: ADl6Iwt0NQT2fgc9Qv1njyr4UrobYFCgGIMfK3lKK4ZEr5JgDHmPtYQNdxr8JGypzYb9YROA+wTdTilow2pBzhoqmhN7TioT41P9VhT4SB/p/fRq5PukU/4BOqeaCt/R4zfi1+vQVLzmTGu/ffqczVZHqd9W12k0ouRhP9yEiCo=
    on:
        tags: true
        node_js: '14'
notifications:
    email: false
