os: linux
dist: focal
language: node_js
node_js:
    - '12'
    - '14'
    - '15'
cache: npm
script:
    - npm run clean
    - npm run prettier-check
    - npm run build
    - npm run test
    - npm run docs
    - ./bin/leasot --help
    - ./bin/leasot-reporter --help
notifications:
    email: false
